# -*- coding: utf-8 -*-
"""qwen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UDpGqlo8XTxvqUYB_y1ai-g_Vd4UqMT
"""

from transformers import AutoModelForCausalLM, AutoTokenizer
device = "cuda" # the device to load the model onto

model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2-7B-Instruct",
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-7B-Instruct")

import json
class DialogueManager:
    def generate_response(self, user_input):
      prompt = f"""
You are an expert at extracting movie metadata and analyzing sentiment.
Output **only** valid JSON with exactly two top-level keys: "metadata" and "sentiment".

REQUIRED JSON STRUCTURE:
{{"metadata": {{...}}, "sentiment": {{"sentiment": "..."}}}}

VALID GENRES ONLY:
• Extract ONLY these as genres: action, thriller, horror, comedy, drama, romance, sci-fi, fantasy, adventure, crime, mystery, documentary, animation, musical, western, war, biography, family, psychological, superhero
• NEVER extract: entertaining, fun, exciting, cheesy, ridiculous, good, great, amazing, awesome, interesting, cool, nice, enjoyable, fantastic, wonderful

STRICT VALIDATION RULES:
• NEVER extract genres that aren't explicitly mentioned using exact genre words
• "entertaining" is NOT a genre - it's descriptive content for review
• "fun" is NOT a genre - it's descriptive content for review
• "cheesy" is NOT a genre - it's descriptive content for review
• "ridiculous" is NOT a genre - it's descriptive content for review
• "enjoyable" is NOT a genre - it's descriptive content for review
• Only extract if user literally says the exact genre word from valid list

"metadata": one flat dictionary —
• If greeting (hi, hello, good morning, etc.): {{"greet": "<exact words>"}}
• If explicit movie metadata (genre, director, actor, year): use those keys
• If no explicit metadata: {{"review": "<direct summary of preferences>"}}
• Extract ALL mentioned entities, including negative context
• NEVER include sentiment inside metadata - keep completely separate

"sentiment": one dictionary with single key "sentiment"
• Key: must be exactly "sentiment"
• Value: comma-separated sentiment matching metadata entity count
• For greetings: "neutral"
• For others: "like", "dislike", "neutral" (lowercase only)

CRITICAL EXTRACTION RULES - NEGATIVE CONTEXT:
• Extract ALL entities mentioned with "not", "but not", "except", "hate", "dislike"
• "I like comedy but not action" → extract BOTH: "comedy, action"
• "I like horror but not romantic" → extract BOTH: "horror, romance"
• "I want action not comedy" → extract BOTH: "action, comedy"
• "I love Nolan but hate Tom Cruise" → extract BOTH: "Nolan" and "Tom Cruise"
• Sentiment reflects the user's feeling toward each entity in order

REVIEW FIELD EXCLUSION RULES:
• DO NOT create review field if input only contains valid genres/directors/actors with no additional descriptive content
• "I like action movies" → ONLY extract genre: "action" (NO review needed)
• "I like comedy and horror" → ONLY extract genre: "comedy, horror" (NO review needed)
• "I like action movies with great stunts" → extract genre: "action" + review: "Movies with great stunts"
• Review field should ONLY exist when there are movie characteristics beyond basic metadata

WHEN TO EXCLUDE REVIEW:
• Input contains only: "I like [genre]", "I want [genre]", "I enjoy [genre]"
• Input contains only genres, actors, directors with basic preference verbs
• NO additional descriptive movie characteristics mentioned

WHEN TO INCLUDE REVIEW:
• Additional characteristics mentioned: "with great stunts", "that are entertaining", "without violence"
• Production companies mentioned: "Marvel films", "Disney movies"
• Movie qualities described: "fast-paced", "character-driven", "well-written"
• Descriptive adjectives: "cheesy", "ridiculous", "fun", "entertaining"

EXTRACTION DECISION LOGIC:
• Input: "I like comedy and horror movies"
  Output: {{"metadata": {{"genre": "comedy, horror"}}, "sentiment": {{"sentiment": "like, like"}}}}
  Reason: Only explicit genres mentioned, no descriptive content

• Input: "I like entertaining comedy movies"
  Output: {{"metadata": {{"genre": "comedy", "review": "Entertaining comedy movies"}}, "sentiment": {{"sentiment": "like, like"}}}}
  Reason: Genre + descriptive content ("entertaining")

• Input: "I want action movies with great car chases"
  Output: {{"metadata": {{"genre": "action", "review": "Movies with great car chases"}}, "sentiment": {{"sentiment": "like, like"}}}}
  Reason: Genre + specific movie characteristic

• Input: "Something entertaining and fun"
  Output: {{"metadata": {{"review": "Entertaining and fun movies"}}, "sentiment": {{"sentiment": "like"}}}}
  Reason: Only descriptive content, no explicit genres

SIMPLE GENRE-ONLY INPUTS (NO REVIEW):
• "I like horror"
• "I want comedy and drama"
• "I enjoy action movies"
• "I prefer thriller films"
• "I like comedy but not action"

SENTIMENT ALIGNMENT RULES:
• Build the sentiment list so its length equals the TOTAL number of metadata entities

How to count entities:
1. For every metadata key:
   - Keys with comma-separated values (genre, actor, director, year)
     → each comma-separated item = 1 entity
     → e.g. "action, comedy, drama" = 3 entities
   - Keys with a single value (greet, review)
     → always count as 1 entity

2. Sum the entities from all keys to get N

3. Provide exactly N comma-separated sentiment words
   - Order must mirror the order the entities appear

EXAMPLES WITH SENTIMENT COUNTS:
• {{"metadata": {{"genre": "horror, romance"}}, "sentiment": {{"sentiment": "like, dislike"}}}}
  → 2 entities, 2 sentiments

• {{"metadata": {{"genre": "superhero, action", "review": "Marvel films with good dialogue"}}, "sentiment": {{"sentiment": "like, like, like"}}}}
  → 2 + 1 = 3 entities, 3 sentiments

• {{"metadata": {{"actor": "Tom Cruise"}}, "sentiment": {{"sentiment": "like"}}}}
  → 1 entity, 1 sentiment

• {{"metadata": {{"review": "Entertaining movies"}}, "sentiment": {{"sentiment": "like"}}}}
  → 1 entity, 1 sentiment

CRITICAL FORMAT RULES:
• NEVER put sentiment inside metadata dictionary
• NEVER duplicate keys in JSON
• Always extract entities mentioned with negative words (not, but not, hate, except)
• Use "romance" not "romantic" as genre
• Keep metadata and sentiment as separate top-level keys only
• Sentiment word choice: Use only: like, dislike, neutral (lowercase)

MANDATORY EXAMPLES FOR NEGATIVE CONTEXT:
• "I like comedy but not action" → {{"metadata": {{"genre": "comedy, action"}}, "sentiment": {{"sentiment": "like, dislike"}}}}
• "I want Christopher Nolan films but not with Tom Cruise" → {{"metadata": {{"director": "Christopher Nolan", "actor": "Tom Cruise"}}, "sentiment": {{"sentiment": "like, dislike"}}}}
• "I love action and comedy movies" → {{"metadata": {{"genre": "action, comedy"}}, "sentiment": {{"sentiment": "like, like"}}}}

Remember:
• Extract ALL entities mentioned, especially those with negative context
• NEVER put sentiment inside metadata
• Always extract both liked AND disliked entities
• Only create review field when descriptive content exists beyond basic genres/actors/directors
• Sentiment count must EXACTLY match total metadata entity count
• Use only lowercase like/dislike/neutral
• NEVER wrap JSON in triple back-ticks
• Keep metadata and sentiment as completely separate top-level keys
• Only extract exact genre words from valid list
• Use review for all descriptive content that isn't a valid genre

User: "{user_input}"
Assistant:
"""
      messages = [
          {"role": "system", "content": "You are a helpful assistant that outputs only valid JSON."},
          {"role": "user", "content": prompt}
      ]

      text = tokenizer.apply_chat_template(
          messages,
          tokenize=False,
          add_generation_prompt=True
      )
      model_inputs = tokenizer([text], return_tensors="pt").to(device)

      generated_ids = model.generate(
          model_inputs.input_ids,
          max_new_tokens=512,
          temperature=0.1,
          do_sample=True
      )
      generated_ids = [
          output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
      ]

      response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
      return response

a = DialogueManager()
while True:
    user_input = input("You: ").strip()

    if user_input.lower() in ['quit', 'exit', 'q']:
        print("👋 Goodbye!")
        break

    response = a.generate_response(user_input)
    raw_json = response.strip()
    data = json.loads(raw_json)
    print(data)

